jwt:
  secret: ${JWT_SECRET}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.MySQLDialect

clova:
  chat-completion:
    api-key: ${CLOVA_CHAT_COMPLETION_API_KEY}
    apigw-key: ${CLOVA_CHAT_COMPLETION_APIGW_KEY}
    request-id: ${CLOVA_CHAT_COMPLETION_REQUEST_ID}
  api:
    client-id: ${CLOVA_API_CLIENT_ID}
    client-secret: ${CLOVA_API_CLIENT_SECRET}

cloud:
  aws:
    s3:
      endpoint: https://kr.object.ncloudstorage.com
    credentials:
      access-key: ${NCP_ACCESS_KEY}
      secret-key: ${NCP_SECRET_KEY}
      bucket: ${NCP_BUCKET_NAME}
    region:
      static: ap-southeast-2
      auto: false
    stack:
      auto: false


pronunciation-similarity-prompt: |
  1. 1번부터 n번까지 입력한 두 단어의 형태소를 분해하여 비교합니다.
  2. 각 단어 쌍의 형태소 유사도를 100점 만점으로 정확하게 측정합니다.
  3. 각 단어 쌍의 유사도 점수의 합을 n으로 나누어 평균을 구합니다.
  4. 이렇게 나온 평균을 반올림하여 숫자로 반환합니다.
  5. 단어가 하나만 주어진 경우, 0을 반환합니다.
  
  평균값 외에 다른 텍스트는 출력하지 마세요.

  
  유사도 계산 기준:
    1. 형태소가 완전히 일치하면 100점.
    2. 하나의 형태소가 다른 하나의 형태소와 일치하면 10점.
    3. 그렇지 않으면 0점.
  
  
  ###
  input:
    1. 바나나, 바나라
    2. 고양이, 고룔이
    3. 안녕하세요, 안넝하세여
    4. 사과, 사가
    5. 컴퓨터, 컴푸타
    6. 전화기, 전확이
    7. 책상, 채상
    8. 텔레비전, 텔래비전
  
  
  output:
    정수
  
  
  ###
  input:
    1. 바나나, 바나나
    2. 사과, 사과
    3. 안녕하세요, 안녕하세요
    4. 책, 책
    5. 의자, 의자
    6. 모니터, 모니터
    7. 마우스, 마우스
    8. 키보드, 키보드
  
  
  output:
    100
  
  
  ###
  input:
    1. <첫 번째 단어>, <두 번째 단어>
    2. <첫 번째 단어>, <두 번째 단어>
    3. <첫 번째 단어>, <두 번째 단어>
    4. <첫 번째 단어>, <두 번째 단어>
    5. <첫 번째 단어>, <두 번째 단어>
    6. <첫 번째 단어>, <두 번째 단어>
    7. <첫 번째 단어>, <두 번째 단어>
    8. <첫 번째 단어>, <두 번째 단어>
  
  
  output:
    정수


  ###
  input:
    1. <첫 번째 단어>, 
  
  
  output:
    0



exercise-create-prompt: |
  입력으로 주어진 상황에 맞는 30자 가량의 발음 연습용 한국어 문장을 생성합니다.
  각 문장은 난도에 맞게 어휘 수준을 조정합니다.
  
  
  난도
  초급
  
  
  간단한 문장 구조(주어 + 동사/형용사) 사용.
  기본적인 시제(현재, 과거, 미래)와 조사 사용.
  기본적인 의문문과 명령문 형식.
  일상적인 단어와 표현 사용.
  자주 쓰이는 기본 명사, 동사, 형용사 사용.
  중급


  복합문과 복잡한 문장 구조 사용(예: 종속절, 접속사 활용).
    다양한 시제와 시제의 혼합(현재진행형, 과거완료형 등).
    명령문, 의문문 외에도 가정법, 조건문, 이유 설명 등.
    어휘는 보다 다양한 동사와 형용사 사용.
    일상 생활에서 사용하는 좀 더 구체적인 단어와 표현.
    고급
  
  
  복잡한 문장 구조와 문법 요소 활용(예: 다양한 연결어, 절의 중첩, 다양한 문장 수식).
  논리적이고 설득적인 표현 사용(예: 가정, 비교, 대조).
    복잡한 조건문, 가정법, 가정적 상황 설명.
    전문 용어와 고급 어휘 사용.
    다양한 추상적인 표현과 숙어, 관용구 사용.
    상황
    [식당에서]
    
    
    음식 주문하기
    추가 주문하기
    메뉴 추천받기
    음식에 대한 불만 표현하기
    계산하기
    예약하기
    [병원 방문]
    
    
    접수하기
    의사에게 증상 말하기
    약국에서 약 처방받기
    진료비 결제하기
    [쇼핑]
    
    
    상품 물어보기
    가격 묻기
    결제하기
    환불/교환 요청하기
    [학교생활]
    
    
    수업 내용 질문하기
    친구와 숙제하기
    도서관에서 책 빌리기
    친구에게 책 추천하기
    [길묻기]
    
    
    교통수단 묻기
    목적지로 가는 길 묻기
    건물 위치 묻기
    길찾기 도중에 방향 묻기
    길 잃어서 도움을 요청하기
    [취미 관심사]
    
    
    취미 소개하기
    공통 취미 찾기
    새로운 취미 만들기
    취미 활동 추천하기
    예시
  input:
    초급, 음식 주문하기
  
  
  output:
    비빔밥 하나 주세요./김치 더 주세요./물 한 잔 주세요./불고기 추가해 주세요.
  
  
  input:
    <난도>, <상황>
  
  
  output:
    예시 문장1/예시 문장2/예시 문장3/예시 문장4

feedback-create-prompt: |
  입력으로 주어진 상황에 맞는 30자 가량의 발음 연습용 한국어 문장을 생성합니다.
  각 문장은 난도에 맞게 어휘 수준을 조정합니다.
  입력으로 주어진 정답 문장, 예시 문장을 분석하여
  틀린 단어 리스트, 점수, 피드백을 생성합니다. 
  틀린 단어는 모두 모아 리스트로 반환합니다. 리스트의 크기는 틀린 단어의 개수입니다.
  틀린 단어가 없으면 틀린 단어 리스트는 빈 리스트를 반환합니다.
  
  점수를 측정하는 기준은 다음과 같습니다.
  1번부터 n번까지 입력한 두 단어의 형태소를 분해하여 비교합니다.
  각 단어 쌍의 형태소 유사도를 100점 만점으로 정확하게 측정합니다.
  각 단어 쌍의 유사도 점수의 합을 n으로 나누어 평균을 구합니다.
  이렇게 나온 평균을 반올림하여 숫자로 반환합니다.
  단어가 하나만 주어진 경우, 0을 반환합니다.
  
  피드백은 아이에게 말하는 것처럼 부드럽게 생성합니다.
  아예 다른 문장이 주어진 경우, score는 0, feedback은 올바른 문장을 입력해 주세요! grading은 빈 리스트를 반환합니다.
  
  예시
  input: 아빠가 새로운 책장을 조립했어요., 아빠가 새로운 색쟝을 죠림했어요.
  
  output:
    {
      "score": 90,
      "feedback": "'책장'과 '조립'의 발음을 정확하게 하는 것이 자연스럽습니다. '책장'의 '책'과 '조립'의 '조'를 강조해서 발음해보세요.",
      "grading": [
        {
          "incorrectWord": "색쟝을",
          "correctWord": "책장을"
        },
        {
          "incorrectWord": "죠림했어요.",
          "correctWord": "조립했어요."
        }
      ]
    }
  
  ###
  
  input:
  오늘 날씨가 매우 좋습니다., 오늘 날씨가 매오 좋습니다.

  output:
    {
      "score": 95,
      "feedback": "'오늘'과 '매우'의 발음을 정확하게 하는 것이 자연스럽습니다. '오늘'의 '오'와 '매우'의 '매'를 강조해서 발음해보세요.",
      "grading": [
        {
          "incorrectWord": "오늘",
          "correctWord": "오늘"
        },
        {
          "incorrectWord": "매오",
          "correctWord": "매우"
        }
      ]
    }

  ###

  input:
  재료가 신선하지 않아요., 양이 너무 적어요.
    
  output:
    {
      "score": 0,
      "feedback": "올바른 문장을 입력해 주세요!",
      "grading": []
    }
  
  ###
  
  input:
  재료가 신선하지 않아요., 양이 너무 적어요.
  
  output:
    {
      "score": 0,
      "feedback": "올바른 문장을 입력해 주세요!",
      "grading": []
    }
  
  ###
  
  input:
  재료가 신선하지 않아요., 양이 너무 적어요.
  
  output:
    {
      "score": 0,
      "feedback": "올바른 문장을 입력해 주세요!",
      "grading": []
    }
  
  ###

  input:
    <정답 문장>, <예시 문장>
  
  output:
    {
      "score": 점수,
      "feedback": 피드백,
      "grading": [
        {
          "incorrectWord": 틀린 단어,
          "correctWord": 정답 단어
        },
        {
          "incorrectWord": 틀린 단어,
          "correctWord": 정답 단어
        },
        {
          "incorrectWord": 틀린 단어,
          "correctWord": 정답 단어
        },
      ]
    }
