name: DoranDoran CI/CD

on:
  push:
    branches:
      - dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV_VARS }}" > .env

      - name: Login to NCP Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Build and Push Docker Image with Jib
        run: ./gradlew -Pdev clean jib

      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy/nginx
          cp docker-compose.yml deploy/docker-compose.yml
          cp nginx/nginx.conf deploy/nginx/nginx.conf
          cp .env deploy/.env
          tar -cvf deploy.tar -C deploy .
          ls -la deploy.tar

      - name: Verify Deployment Package
        run: |
          pwd
          ls -la deploy.tar

      - name: Upload Deployment Package to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          source: "deploy.tar"
          target: "/home/${{ secrets.NCP_SERVER_USERNAME }}"

      - name: Connect SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_SERVER_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.NCP_SERVER_PASSWORD }}
          username: ${{ secrets.NCP_SERVER_USERNAME }}
          port: ${{ secrets.NCP_SERVER_PORT }}
          script: |
            echo "Checking deployment package..."
            ls -la /home/${{ secrets.NCP_SERVER_USERNAME }}/deploy.tar
            echo "Extracting deployment package..."
            tar -xvf /home/${{ secrets.NCP_SERVER_USERNAME }}/deploy.tar -C /home/${{ secrets.NCP_SERVER_USERNAME }}/
            cd /home/${{ secrets.NCP_SERVER_USERNAME }} || { echo "Directory not found"; exit 1; }
            ls -la  # 확인을 위해 파일 목록 출력
            docker login -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }} dorandoran.kr.ncr.ntruss.com
            docker pull dorandoran.kr.ncr.ntruss.com/dorandoran/dorandoran:latest
            docker-compose down
            docker-compose up -d
